added fix

diff --git a/Jenkinsfile.oke b/Jenkinsfile.oke
--- a/Jenkinsfile.oke
+++ b/Jenkinsfile.oke
@@ -98,12 +98,11 @@ pipeline {
         )
         string(name: 'WDT_DOWNLOAD_URL',
                description: 'URL to download WDT.',
-               defaultValue: 'https://objectstorage.us-phoenix-1.oraclecloud.com/n/weblogick8s/b/wko-system-test-files/o/weblogic-deploy-main.zip'
+               defaultValue: 'https://github.com/oracle/weblogic-deploy-tooling/releases/latest'
         )
         string(name: 'WIT_DOWNLOAD_URL',
                description: 'URL to download WIT.',
-               defaultValue: 'https://objectstorage.us-phoenix-1.oraclecloud.com/n/weblogick8s/b/wko-system-test-files/o/imagetool-main.zip'
-        )
+               defaultValue: 'https://github.com/oracle/weblogic-image-tool/releases/latest'
         string(name: 'REPO_REGISTRY',
                description: '',
                defaultValue: 'phx.ocir.io'
@@ -420,25 +419,8 @@ EOF
                 stage('Run integration tests') {
                     environment {
                         runtime_path = "${WORKSPACE}/bin:${PATH}"
-                        IMAGE_PULL_SECRET_WEBLOGIC = credentials("${image_pull_secret_weblogic_creds}")
-                        OCR_USERNAME = credentials("${ocr_username_creds}")
-                        OCR_PASSWORD = credentials("${ocr_password_creds}")
-                        OCR_EMAIL = credentials("${ocr_username_creds}")
-                        OCIR_REGISTRY = credentials("${ocir_registry_creds}")
-                        OCIR_USERNAME = credentials("${ocir_username_creds}")
-                        OCIR_PASSWORD = credentials("${ocir_password_creds}")
-                        OCIR_EMAIL = credentials("${ocir_email_creds}")
                         OKE_SSH_PRIVATE_KEY = credentials("${oke_test_ssh_pk}")
-                        BASE_IMAGES_REPO_USERNAME = credentials("${ocir_username_creds}")
-                        BASE_IMAGES_REPO_PASSWORD = credentials("${ocir_password_creds}")
-                        BASE_IMAGES_REPO_EMAIL = credentials("${ocir_email_creds}")
-                        TEST_IMAGES_REPO_USERNAME = credentials("${ocir_username_creds}")
-                        TEST_IMAGES_REPO_PASSWORD = credentials("${ocir_password_creds}")
-                        TEST_IMAGES_REPO_EMAIL = credentials("${ocir_email_creds}")
                         compartment_ocid = credentials("${weblogick8s_qa_compartment_ocid}")
-                        DOMAIN_IMAGES_REPO = "phx.ocir.io"
-                        BASE_IMAGES_REPO = "phx.ocir.io"
-                        REPO_REGISTRY = "phx.ocir.io"
                         clusterName = "${CLUSTER_NAME}"
                         FSS_DIR = "/oketest1,/oketest2,/oketest3,/oketest4,/oketest5,/oketest6,/oketest7,/oketest8,/oketest9,/oketest10,/oketest11,/oketest12,/oketest13,/oketest14,/oketest15"
 
@@ -505,20 +487,22 @@ EOF
                             echo "-Dwko.it.result.root=\"${result_root}\""                                               >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.pv.root=\"${pv_root}\""                                                       >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.k8s.nodeport.host=\"${K8S_NODEPORT_HOST}\""                                   >> ${WORKSPACE}/.mvn/maven.config
+                            echo "-Dwko.it.kind.repo=\"localhost:${registry_port}\""                                     >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.istio.version=\"${ISTIO_VERSION}\""                                           >> ${WORKSPACE}/.mvn/maven.config
                             echo "-DPARALLEL_CLASSES=\"${PARALLEL_RUN}\""                                                >> ${WORKSPACE}/.mvn/maven.config
                             echo "-DNUMBER_OF_THREADS=\"${NUMBER_OF_THREADS}\""                                          >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.wdt.download.url=\"${WDT_DOWNLOAD_URL}\""                                     >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.wit.download.url=\"${WIT_DOWNLOAD_URL}\""                                     >> ${WORKSPACE}/.mvn/maven.config
-                            echo "-Dwko.it.repo.registry=\"${REPO_REGISTRY}\""                                           >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.base.images.repo=\"${BASE_IMAGES_REPO}\""                                     >> ${WORKSPACE}/.mvn/maven.config
+                            echo "-Dwko.it.base.images.tenancy=\"${wko_tenancy}\""                                       >> ${WORKSPACE}/.mvn/maven.config
+                            echo "-Dwko.it.test.images.repo=\"${TEST_IMAGES_REPO}\""                                     >> ${WORKSPACE}/.mvn/maven.config
+                            echo "-Dwko.it.test.images.tenancy=\"${wko_tenancy}\""                                       >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.weblogic.image.name=\"${WEBLOGIC_IMAGE_NAME}\""                               >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.weblogic.image.tag=\"${WEBLOGIC_IMAGE_TAG}\""                                 >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.fmwinfra.image.name=\"${FMWINFRA_IMAGE_NAME}\""                               >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.fmwinfra.image.tag=\"${FMWINFRA_IMAGE_TAG}\""                                 >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.db.image.name=\"${DB_IMAGE_NAME}\""                                           >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.db.image.tag=\"${DB_IMAGE_TAG}\""                                             >> ${WORKSPACE}/.mvn/maven.config
-                            echo "-Dwko.it.test.images.repo=\"${TEST_IMAGES_REPO}\""                                     >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.monitoring.exporter.branch=\"${MONITORING_EXPORTER_BRANCH}\""                 >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.monitoring.exporter.webapp.version=\"${MONITORING_EXPORTER_WEBAPP_VERSION}\"" >> ${WORKSPACE}/.mvn/maven.config
                             echo "-Dwko.it.prometheus.chart.version=\"${PROMETHEUS_CHART_VERSION}\""                     >> ${WORKSPACE}/.mvn/maven.config
@@ -528,44 +512,29 @@ EOF
                             echo "${WORKSPACE}/.mvn/maven.config contents:"
                             cat "${WORKSPACE}/.mvn/maven.config"
                             cp "${WORKSPACE}/.mvn/maven.config" "${result_root}"
-
-                            export OCR_USERNAME=${OCR_USERNAME}
-                            export OCR_PASSWORD=${OCR_PASSWORD}
-                            export OCR_EMAIL=${OCR_EMAIL}
-                            export OCIR_USERNAME=${OCIR_USERNAME}
-                            export OCIR_PASSWORD=${OCIR_PASSWORD}
-                            export OCIR_EMAIL=${OCIR_EMAIL}
-                            export DOMAIN_IMAGES_REPO=${DOMAIN_IMAGES_REPO}
-                            export BASE_IMAGES_REPO=${BASE_IMAGES_REPO}
-                            export OKE_CLUSTER="true"
-                            export OKD="false"
-                            export BASE_IMAGES_REPO_USERNAME=${BASE_IMAGES_REPO_USERNAME}
-                            export BASE_IMAGES_REPO_PASSWORD=${BASE_IMAGES_REPO_PASSWORD}
-                            export BASE_IMAGES_REPO_EMAIL=${BASE_IMAGES_REPO_EMAIL}
-
-
-                            if [ ! -z "${http_proxy}" ]; then
-                                export http_proxy
-                            elif [ ! -z "${HTTP_PROXY}" ]; then
-                                export HTTP_PROXY
-                            fi
-
-                            if [ ! -z "${https_proxy}" ]; then
-                                export https_proxy
-                            elif [ ! -z "${HTTPS_PROXY}" ]; then
-                                export HTTPS_PROXY
-                            fi
-
-                            if [ ! -z "${no_proxy}" ]; then
-                                export no_proxy
-                            elif [ ! -z "${NO_PROXY}" ]; then
-                                export NO_PROXY
-                            fi
-
-                            if ! mvn -pl integration-tests -P ${MAVEN_PROFILE_NAME} verify 2>&1 | tee "${result_root}/oketest.log"; then
-                                echo "integration-tests failed"
-                            fi
                         '''
+                       withMaven(globalMavenSettingsConfig: 'wkt-maven-settings-xml', publisherStrategy: 'EXPLICIT') {
+                            withCredentials([
+                                usernamePassword(credentialsId: "${ocir_creds}", usernameVariable: 'OCIR_USER', passwordVariable: 'OCIR_PASS')
+                            ]) {
+                                sh '''
+                                    export PATH=${runtime_path}
+                                    export OKE_CLUSTER="true"
+                                    export OKD="false"
+                                    export KUBECONFIG=${kubeconfig_file}
+                                    export BASE_IMAGES_REPO_USERNAME="${OCIR_USER}"
+                                    export BASE_IMAGES_REPO_PASSWORD="${OCIR_PASS}"
+                                    export BASE_IMAGES_REPO_EMAIL="noreply@oracle.com"
+                                    export TEST_IMAGES_REPO_USERNAME="${OCIR_USER}"
+                                    export TEST_IMAGES_REPO_PASSWORD="${OCIR_PASS}"
+                                    export TEST_IMAGES_REPO_EMAIL="noreply@oracle.com"
+                                    if ! mvn -pl integration-tests -P ${MAVEN_PROFILE_NAME} verify 2>&1 | tee "${result_root}/oketest.log"; then
+                                        echo "integration-tests failed"
+                                        exit 1
+                                    fi
+                                '''
+                            }
+                       }
                     }
                     post {
                         always {
@@ -580,6 +549,7 @@ EOF
                                 sudo mv -f ${result_root}/* "${WORKSPACE}/logdir/${BUILD_TAG}/wl_k8s_test_results"
                                 ${WORKSPACE}/terraform/oke.delete.sh ${OCI_PROP_FILE} ${WORKSPACE}/terraform
                             '''
+
                             archiveArtifacts(artifacts: "logdir/**/*")
                             junit(testResults: 'integration-tests/target/failsafe-reports/*.xml', allowEmptyResults: true)
                         }
